import { describe, expect, it, vi } from 'vitest'
import { FrontendHost } from '../src/host.ts'
import type { FrontendProvider } from '../src/provider.ts'

function provider(id: string, events: string[], fail = false): FrontendProvider<{ readonly token: string }> {
  return { id, capture: () => { events.push(`${id}:capture`); return { token: 'state' } }, activate: (ctx) => { events.push(`${id}:activate`); if (fail) throw new Error('bad'); ctx.publish({ providerId: id, capabilities: [], views: [] }); }, restore: () => { events.push(`${id}:restore`) }, dispose: () => { events.push(`${id}:dispose`) } }
}
describe('FrontendHost', () => {
  it('runs lifecycle and restores state on swap', async () => { const events: string[] = []; const host = new FrontendHost(); await host.activateInitial(provider('a', events)); await host.swap(provider('b', events)); expect(events).toEqual(['a:activate', 'a:capture', 'a:dispose', 'b:activate', 'b:restore']); expect(host.snapshot.providerId).toBe('b') })
  it('falls back to plain when activation fails', async () => { const events: string[] = []; const host = new FrontendHost(); await host.swap(provider('bad', events, true)); expect(host.currentProvider.id).toBe('plain'); expect(host.snapshot.providerId).toBe('plain') })
  it('supports providers without capture or restore and exposes current context', async () => { const host = new FrontendHost(); let current = false; await host.activateInitial({ id: 'minimal', activate: ctx => { current = ctx.isCurrent(); ctx.publish({ providerId: 'minimal', capabilities: [], views: [] }) } }); expect(current).toBe(true); await host.swap({ id: 'empty', activate: () => undefined }); expect(host.currentProvider.id).toBe('empty') })
  it('ignores late events after unload', async () => { const host = new FrontendHost(); let publish!: () => void; const late: FrontendProvider = { id: 'late', activate: ctx => { ctx.publish({ providerId: 'late', capabilities: [], views: [{ kind: 'text', text: 'initial' }] }); publish = () => ctx.publish({ providerId: 'late', capabilities: [], views: [{ kind: 'text', text: 'late' }] }) } }; await host.activateInitial(late); await host.unload(); publish(); expect(host.snapshot.providerId).toBe('plain'); expect(host.snapshot.views).toEqual([]) })
  it('unsubscribes model listeners', async () => { const host = new FrontendHost(); const listener = vi.fn(); const off = host.subscribe(listener); off(); await host.unload(); expect(listener).toHaveBeenCalledTimes(1) })
  it('notifies active listeners for published models', async () => { const host = new FrontendHost(); const listener = vi.fn(); host.subscribe(listener); await host.activateInitial({ id: 'publishing', activate: ctx => ctx.publish({ providerId: 'publishing', capabilities: ['text'], views: [{ kind: 'text', text: 'ready' }] }) }); expect(listener).toHaveBeenLastCalledWith(host.snapshot); expect(host.snapshot.providerId).toBe('publishing') })
  it('makes unload and post-unload swap idempotent', async () => { const host = new FrontendHost(); const dispose = vi.fn(); await host.activateInitial({ id: 'owned', activate: () => undefined, dispose }); await host.unload(); await host.unload(); await host.swap({ id: 'ignored', activate: () => undefined }); expect(dispose).toHaveBeenCalledTimes(1); expect(host.currentProvider.id).toBe('plain'); expect(host.snapshot.providerId).toBe('plain') })
  it('rejects a failed capture and continues draining queued swaps', async () => { const host = new FrontendHost(); await host.activateInitial({ id: 'broken', capture: async () => { throw new Error('capture failed') }, activate: () => undefined }); await expect(host.swap({ id: 'next', activate: () => undefined })).rejects.toThrow('capture failed'); expect(host.currentProvider.id).toBe('broken') })
  it('stops a swap when unload completes during capture', async () => { const host = new FrontendHost(); let release!: () => void; const dispose = vi.fn(); await host.activateInitial({ id: 'owned', activate: () => undefined, capture: () => new Promise(resolve => { release = () => resolve({}); }), dispose }); const pending = host.swap({ id: 'next', activate: () => undefined }); await Promise.resolve(); await host.unload(); release(); await pending; expect(dispose).toHaveBeenCalledTimes(1); expect(host.currentProvider.id).toBe('plain') })
  it('does not activate after unload starts during disposal', async () => { const host = new FrontendHost(); let unloading = false; const dispose = vi.fn(() => { if (!unloading) { unloading = true; void host.unload() } }); await host.activateInitial({ id: 'owned', activate: () => undefined, dispose }); await host.swap({ id: 'next', activate: () => undefined }); expect(host.currentProvider.id).toBe('plain') })
})
