import { describe, expect, it, vi } from 'vitest'
import { probeCapabilities } from '../src/capabilities.ts'
import { ActionCoordinator } from '../src/action.ts'
import { ModelBridge } from '../src/model.ts'
import { ProjectionBridge } from '../src/projection.ts'
import { QuestionBridge } from '../src/question.ts'
import { SessionBridge } from '../src/session.ts'
import { apply as invariantApply, name as invariantName } from '../src/invariant.ts'
import { actionPlugin, apply as rootApply, modelPlugin, projectionPlugin, questionPlugin, sessionPlugin } from '../src/plugins.ts'

const snapshot = (id = 's1') => ({ id, cwd: '/tmp', status: 'idle' as const, mode: 'normal' as const })

describe('capability probing', () => {
  it('supports declared and method-based capabilities and explicit absent', () => {
    const declared = probeCapabilities({ capabilities: ['model'] }, ['model', 'session'])
    expect(declared.present).toEqual(['model']); expect(declared.has('session')).toBe(false); expect(declared.require('session')?.kind).toBe('absent')
    const method = probeCapabilities({ hasCapability: value => value === 'session' }, ['session', 'model'])
    expect(method.present).toEqual(['session']); expect(method.absent[0]?.capability).toBe('model')
  })
})

describe('SessionBridge', () => {
  it('attaches after a watermark, accepts only newer matching events, and detaches', async () => {
    let listener: ((event: { seq: number; sessionId: string; event: ReturnType<typeof snapshot> }) => void) | undefined
    const source = { snapshot: vi.fn(async () => ({ watermark: 4, value: snapshot() })), subscribe: vi.fn((_watermark: number, next: typeof listener) => { listener = next; return () => { listener = undefined } }), request: vi.fn(async () => undefined) }
    const bridge = new SessionBridge({ source }); const seen: string[] = []; const registration = bridge.subscribe(value => seen.push(value?.id ?? 'none')); await expect(bridge.attach()).resolves.toMatchObject({ ok: true }); expect(bridge.sessionEpoch).toBe(1); expect(bridge.attached).toBe(true); listener?.({ seq: 4, sessionId: 's1', event: { ...snapshot(), cwd: 'old' } }); listener?.({ seq: 5, sessionId: 'other', event: snapshot('other') }); listener?.({ seq: 6, sessionId: 's1', event: { ...snapshot(), cwd: '/work' } }); expect(bridge.current()?.cwd).toBe('/work'); expect(seen).toEqual(['none', 's1', 's1']); expect(registration.disposed).toBe(false); registration.dispose(); registration.dispose(); expect(registration.disposed).toBe(true); bridge.detach(); expect(bridge.current()).toBeNull(); expect(source.subscribe).toHaveBeenCalledWith(4, expect.any(Function))
  })
  it('returns absent without a source, maps request errors and rejects stale results', async () => {
    const absentBridge = new SessionBridge(); await expect(absentBridge.attach()).resolves.toMatchObject({ ok: false, code: 'BLUE_CAPABILITY_ABSENT' }); await expect(absentBridge.request({ kind: 'interrupt' })).resolves.toMatchObject({ code: 'BLUE_SESSION_UNAVAILABLE' })
    let release!: () => void; let calls = 0; const source = { snapshot: async () => ({ watermark: 0, value: snapshot() }), subscribe: () => () => undefined, request: vi.fn(async () => { calls++; if (calls === 1) return; await new Promise<void>(resolve => { release = resolve }) }) }; const bridge = new SessionBridge({ source }); await bridge.attach(); await expect(bridge.request({ kind: 'interrupt' })).resolves.toMatchObject({ ok: true }); const pending = bridge.request({ kind: 'interrupt' }); bridge.detach(); release(); await expect(pending).resolves.toMatchObject({ code: 'BLUE_ACTION_REJECTED' }); source.request.mockRejectedValueOnce(new Error('failed')); await bridge.attach(); await expect(bridge.request({ kind: 'interrupt' })).resolves.toMatchObject({ code: 'BLUE_ACTION_REJECTED' }); source.request.mockRejectedValueOnce('string failure'); await expect(bridge.request({ kind: 'interrupt' })).resolves.toMatchObject({ code: 'BLUE_ACTION_REJECTED', message: 'string failure' }); const preAbort = new AbortController(); preAbort.abort(); await expect(bridge.request({ kind: 'interrupt' }, { signal: preAbort.signal })).resolves.toMatchObject({ code: 'BLUE_ABORTED' }); expect(bridge.sessionEpoch).toBe(3)
  })
  it('maps an aborted request and cleans registrations on dispose', async () => {
    const source = { snapshot: async () => ({ watermark: 0, value: snapshot() }), subscribe: () => () => undefined, request: vi.fn((_action: unknown, signal: AbortSignal) => new Promise<void>((_resolve, reject) => signal.addEventListener('abort', () => reject(new Error('aborted')), { once: true }))) }; const bridge = new SessionBridge({ source }); await bridge.attach(); const controller = new AbortController(); const pending = bridge.request({ kind: 'interrupt' }, { signal: controller.signal }); controller.abort(); await expect(pending).resolves.toMatchObject({ code: 'BLUE_ABORTED' }); bridge.dispose(); expect(bridge.attached).toBe(false)
  })
  it('rejects an attach whose snapshot is aborted', async () => { let bridge!: SessionBridge; const source = { snapshot: async (signal: AbortSignal) => { queueMicrotask(() => bridge.detach()); await new Promise<void>(resolve => signal.addEventListener('abort', () => resolve(), { once: true })); return { watermark: 0, value: snapshot() } }, subscribe: () => () => undefined, request: async () => undefined }; bridge = new SessionBridge({ source }); await expect(bridge.attach()).resolves.toMatchObject({ code: 'BLUE_ABORTED' }) })
})

describe('ProjectionBridge', () => {
  it('replays a baseline and applies only post-watermark events', async () => {
    let listener!: (event: { seq: number; sessionId: string; event: number }) => void; const source = { snapshot: async () => ({ watermark: 2, value: [1, 2] }), subscribe: (_id: string, _seq: number, next: typeof listener) => { listener = next; return () => undefined } }; const bridge = new ProjectionBridge({ init: () => 0, apply: (state, event) => state + event }, source); const updates: number[] = []; const off = bridge.subscribe(state => updates.push(state)); await expect(bridge.attach('s1')).resolves.toMatchObject({ ok: true, value: 3 }); listener({ seq: 2, sessionId: 's1', event: 4 }); listener({ seq: 3, sessionId: 'other', event: 9 }); listener({ seq: 4, sessionId: 's1', event: 5 }); expect(bridge.snapshot.state).toBe(8); off(); listener({ seq: 5, sessionId: 's1', event: 10 }); bridge.dispose(); expect(bridge.snapshot.state).toBeUndefined()
  })
  it('returns absent without a source', async () => { const bridge = new ProjectionBridge({ init: () => 0, apply: (state: number, event: number) => state + event }); await expect(bridge.attach('s1')).resolves.toMatchObject({ code: 'BLUE_CAPABILITY_ABSENT' }); bridge.dispose() })
  it('drops an attach aborted during baseline loading', async () => { let bridge!: ProjectionBridge<number, number>; const source = { snapshot: async (id: string, signal: AbortSignal) => { queueMicrotask(() => bridge.detach()); await new Promise<void>(resolve => signal.addEventListener('abort', () => resolve(), { once: true })); return { watermark: 0, value: [] } }, subscribe: () => () => undefined }; bridge = new ProjectionBridge({ init: () => 0, apply: (state, event) => state + event }, source); await expect(bridge.attach('s1')).resolves.toMatchObject({ code: 'BLUE_ABORTED' }) })
})

describe('ActionCoordinator', () => {
  it('queues actions and rejects stale results after a session switch', async () => { const coordinator = new ActionCoordinator(); const order: number[] = []; const first = coordinator.execute('main', async ({ signal }) => { await new Promise<void>(resolve => setTimeout(resolve, 1)); expect(signal.aborted).toBe(false); order.push(1); return 'one' }); const second = coordinator.execute('main', async () => { order.push(2); return 'two' }); await expect(first).resolves.toMatchObject({ ok: true, value: 'one' }); await expect(second).resolves.toMatchObject({ ok: true, value: 'two' }); expect(order).toEqual([1, 2]); const stale = coordinator.execute('main', async () => 'late'); coordinator.switchSession(); await expect(stale).resolves.toMatchObject({ code: 'BLUE_ACTION_REJECTED' }); const running = coordinator.execute('main', async () => new Promise<string>(resolve => setTimeout(() => resolve('late'), 1))); await Promise.resolve(); coordinator.switchSession(); await expect(running).resolves.toMatchObject({ code: 'BLUE_ACTION_REJECTED' }) })
  it('maps abort and handler errors', async () => { const coordinator = new ActionCoordinator(); const controller = new AbortController(); const aborted = coordinator.execute('main', async ({ signal }) => new Promise<string>((_resolve, reject) => signal.addEventListener('abort', () => reject(new Error('abort')), { once: true })), { signal: controller.signal }); controller.abort(); await expect(aborted).resolves.toMatchObject({ code: 'BLUE_ABORTED' }); const runningController = new AbortController(); const running = coordinator.execute('main', async ({ signal }) => new Promise<string>((_resolve, reject) => signal.addEventListener('abort', () => reject(new Error('abort')), { once: true })), { signal: runningController.signal }); await Promise.resolve(); runningController.abort(); await expect(running).resolves.toMatchObject({ code: 'BLUE_ABORTED' }); await expect(coordinator.execute('btw', async () => { throw new Error('bad') })).resolves.toMatchObject({ code: 'BLUE_ACTION_REJECTED' }); await expect(coordinator.execute('btw', async () => { throw 'bad' })).resolves.toMatchObject({ code: 'BLUE_ACTION_REJECTED', message: 'bad' }); coordinator.dispose(); expect(coordinator.sessionEpoch).toBe(1) })
})

describe('model and question bridges', () => {
  it('probes model capability and maps abort/errors', async () => { const absentModel = new ModelBridge(); await expect(absentModel.list()).resolves.toMatchObject({ code: 'BLUE_CAPABILITY_ABSENT' }); const noCapability = new ModelBridge({ capabilities: [], listModels: async () => [] }); await expect(noCapability.list()).resolves.toMatchObject({ code: 'BLUE_CAPABILITY_ABSENT' }); const source = { capabilities: ['model'], listModels: vi.fn(async () => ['a', 'b']) }; const bridge = new ModelBridge(source); await expect(bridge.list()).resolves.toMatchObject({ ok: true, value: ['a', 'b'] }); source.listModels.mockRejectedValueOnce(new Error('down')); await expect(bridge.list()).resolves.toMatchObject({ code: 'BLUE_ACTION_REJECTED' }); source.listModels.mockRejectedValueOnce('string failure'); await expect(bridge.list()).resolves.toMatchObject({ code: 'BLUE_ACTION_REJECTED', message: 'string failure' }); const controller = new AbortController(); controller.abort(); await expect(bridge.list(controller.signal)).resolves.toMatchObject({ code: 'BLUE_ABORTED' }); bridge.dispose() })
  it('supports question/approval and absent fallback', async () => { const absentBridge = new QuestionBridge<string, string>(); await expect(absentBridge.ask('q')).resolves.toMatchObject({ code: 'BLUE_CAPABILITY_ABSENT' }); await expect(absentBridge.approve('q')).resolves.toMatchObject({ code: 'BLUE_CAPABILITY_ABSENT' }); absentBridge.dispose(); const bridge = new QuestionBridge({ ask: async (q: string) => `answer:${q}`, approve: async () => 'yes' }); await expect(bridge.ask('q')).resolves.toMatchObject({ ok: true, value: 'answer:q' }); await expect(bridge.approve('q')).resolves.toMatchObject({ ok: true, value: 'yes' }); const failing = new QuestionBridge({ ask: async () => { throw new Error('down') } }); await expect(failing.ask('q')).resolves.toMatchObject({ code: 'BLUE_ACTION_REJECTED' }); const stringFailing = new QuestionBridge({ ask: async () => { throw 'down' } }); await expect(stringFailing.ask('q')).resolves.toMatchObject({ code: 'BLUE_ACTION_REJECTED', message: 'down' }); const runningController = new AbortController(); const running = new QuestionBridge({ ask: async (_q: string, signal: AbortSignal) => new Promise<string>((_resolve, reject) => signal.addEventListener('abort', () => reject(new Error('abort')), { once: true })) }); const pending = running.ask('q', { signal: runningController.signal }); await Promise.resolve(); runningController.abort(); await expect(pending).resolves.toMatchObject({ code: 'BLUE_ABORTED' }); const controller = new AbortController(); controller.abort(); const slow = new QuestionBridge({ ask: async (_q: string, signal: AbortSignal) => { await new Promise<void>(resolve => setTimeout(resolve, 1)); if (signal.aborted) throw new Error('abort'); return 'x' } }); await expect(slow.ask('q', { signal: controller.signal })).resolves.toMatchObject({ code: 'BLUE_ABORTED' }); bridge.dispose() })
  })

describe('Cordis plugin entries', () => {
  it('provides independently disposable adapter fibers', () => { const provided = new Map<string, { dispose(): void }>(); const cleanups: (() => void)[] = []; const ctx = { provide: (key: string, value: { dispose(): void }) => { provided.set(key, value) }, effect: (effect: () => () => void) => { cleanups.push(effect()); return cleanups.at(-1) }, plugin: (plugin: { apply(ctx: never): void }) => plugin.apply(ctx as never) } as never; sessionPlugin().apply(ctx); actionPlugin().apply(ctx); projectionPlugin(new ProjectionBridge({ init: () => 0, apply: (state: number) => state })).apply(ctx); modelPlugin(new ModelBridge({ capabilities: ['model'], listModels: async () => [] })).apply(ctx); questionPlugin(new QuestionBridge({ ask: async () => 'ok' })).apply(ctx); rootApply(ctx); expect(provided.has('blueHarnessSessionAdapter')).toBe(true); for (const cleanup of cleanups) cleanup(); expect(invariantName).toBe('blue-harness-adapter-invariant'); expect(() => invariantApply(ctx)).not.toThrow() })
})
