import { describe, expect, it, vi } from 'vitest'
import { ActionCoordinator, SessionBridge } from '@dsh-blue/blue-harness-adapter'
import { CurrentSessionBinding } from '../src/binding.ts'
import { RemoteSessionAdapter } from '../src/adapter.ts'
import { ProjectionRegistry } from '../src/registry.ts'
import { apply, projectionRegistryPlugin, sessionRuntimePlugin } from '../src/plugins.ts'
import { apply as invariantApply, name as invariantName } from '../src/invariant.ts'
import type { RemoteTransport } from '../src/types.ts'

const snap = (id = 's1') => ({ id, cwd: '/tmp', status: 'idle' as const, mode: 'normal' as const })

function transportFixture() {
    const eventListeners = new Map<string, (event: { seq: number; sessionId: string; event: ReturnType<typeof snap> }) => void>()
  const transport: RemoteTransport = {
    negotiate: vi.fn(async () => ({ protocol: '1', capabilities: ['session', 'action', 'projection', 'question', 'approval', 'writeLease'] as const })),
    snapshot: vi.fn(async () => ({ watermark: 4, value: snap() })),
    subscribe: vi.fn((id, _after, listener) => { eventListeners.set(id, listener); return () => { if (eventListeners.get(id) === listener) eventListeners.delete(id) } }),
    request: vi.fn(async () => undefined),
    acquireWriteLease: vi.fn(async () => ({ token: 'lease', expiresAt: 10 })),
    releaseWriteLease: vi.fn(async () => undefined),
    ask: vi.fn(async (_id, question) => `answer:${String(question)}`),
    approve: vi.fn(async () => 'yes'),
  }
  return { transport, emit: (event: { seq: number; sessionId: string; event: ReturnType<typeof snap> }) => eventListeners.get(event.sessionId)?.(event) }
}

describe('RemoteSessionAdapter', () => {
  it('negotiates, resumes from the snapshot watermark, and drops late events', async () => {
    const fixture = transportFixture(); const adapter = new RemoteSessionAdapter(fixture.transport); const seen: string[] = []
    await expect(adapter.connect('s1')).resolves.toMatchObject({ ok: true, value: snap() }); expect(adapter.protocol).toBe('1'); expect(adapter.sessionId).toBe('s1')
    const off = adapter.subscribe(4, event => seen.push(event.event.cwd)); fixture.emit({ seq: 4, sessionId: 's1', event: { ...snap(), cwd: 'old' } }); fixture.emit({ seq: 5, sessionId: 'other', event: { ...snap('other'), cwd: 'other' } }); fixture.emit({ seq: 6, sessionId: 's1', event: { ...snap(), cwd: '/work' } }); expect(seen).toEqual(['/work']); expect(fixture.transport.subscribe).toHaveBeenCalledWith('s1', 4, expect.any(Function)); off(); off(); adapter.disconnect(); fixture.emit({ seq: 7, sessionId: 's1', event: snap() }); expect(seen).toEqual(['/work']); const unavailableOff = adapter.subscribe(0, () => undefined); unavailableOff(); expect(adapter.capabilities).toEqual([])
  })
  it('returns absent, abort, and structured transport failures', async () => {
    const absentTransport: RemoteTransport = { negotiate: async () => ({ protocol: '1', capabilities: [] }), snapshot: async () => ({ watermark: 0, value: snap() }), subscribe: () => () => undefined, request: async () => undefined }
    await expect(new RemoteSessionAdapter(absentTransport).connect('s1')).resolves.toMatchObject({ code: 'BLUE_CAPABILITY_ABSENT', capability: 'session' })
    const controller = new AbortController(); controller.abort(); const aborted = new RemoteSessionAdapter(transportFixture().transport); await expect(aborted.connect('s1', controller.signal)).resolves.toMatchObject({ code: 'BLUE_ABORTED' })
    const bad: RemoteTransport = { ...absentTransport, negotiate: async () => { throw new Error('network') } }; await expect(new RemoteSessionAdapter(bad).connect('s1')).resolves.toMatchObject({ code: 'BLUE_API_INCOMPATIBLE', message: 'network' }); const stringBad: RemoteTransport = { ...absentTransport, negotiate: async () => { throw 'network' } }; await expect(new RemoteSessionAdapter(stringBad).connect('s1')).resolves.toMatchObject({ code: 'BLUE_API_INCOMPATIBLE', message: 'network' }); let rejectOnAbort!: (error: unknown) => void; const abortBad: RemoteTransport = { ...absentTransport, negotiate: async signal => new Promise((_resolve, reject) => { rejectOnAbort = reject; signal.addEventListener('abort', () => rejectOnAbort(new Error('aborted')), { once: true }) }) }; const abortBadAdapter = new RemoteSessionAdapter(abortBad); const abortBadPending = abortBadAdapter.connect('s1'); abortBadAdapter.disconnect(); await expect(abortBadPending).resolves.toMatchObject({ code: 'BLUE_ABORTED' })
    const fixture = transportFixture(); const adapter = new RemoteSessionAdapter(fixture.transport); await adapter.connect('s1'); await expect(adapter.request({ kind: 'interrupt' }, new AbortController().signal)).resolves.toBeUndefined(); await expect(adapter.acquireWriteLease()).resolves.toMatchObject({ ok: true, value: { token: 'lease' } }); await expect(adapter.releaseWriteLease()).resolves.toMatchObject({ ok: true }); expect(adapter.questionSource()).toBeDefined(); await expect(adapter.questionSource()!.ask('q', new AbortController().signal)).resolves.toBe('answer:q'); await expect(adapter.questionSource()!.approve('q', new AbortController().signal)).resolves.toBe('yes'); adapter.dispose()
    const snapshotBad = { ...absentTransport, negotiate: async () => ({ protocol: '1', capabilities: ['session'] as const }), snapshot: async () => { throw new Error('snapshot down') } }; await expect(new RemoteSessionAdapter(snapshotBad).connect('s1')).resolves.toMatchObject({ code: 'BLUE_API_INCOMPATIBLE', message: 'snapshot down' }); let resolveNegotiation!: (value: { protocol: string; capabilities: readonly ['session'] }) => void; const slow: RemoteTransport = { ...absentTransport, negotiate: async () => new Promise(resolve => { resolveNegotiation = resolve }) }; const slowAdapter = new RemoteSessionAdapter(slow); const connecting = slowAdapter.connect('s1'); slowAdapter.disconnect(); resolveNegotiation({ protocol: '1', capabilities: ['session'] }); await expect(connecting).resolves.toMatchObject({ code: 'BLUE_ABORTED' })
  })
  it('handles optional lease/question capability and abort/error paths', async () => {
    const fixture = transportFixture(); const transport = { ...fixture.transport, negotiate: async () => ({ protocol: '1', capabilities: ['session', 'action', 'writeLease'] as const }), acquireWriteLease: async (_id: string, signal: AbortSignal) => { if (signal.aborted) throw new Error('aborted'); throw new Error('lease down') }, releaseWriteLease: async () => { throw new Error('release down') } }; const adapter = new RemoteSessionAdapter(transport); await adapter.connect('s1'); await expect(adapter.acquireWriteLease()).resolves.toMatchObject({ code: 'BLUE_ACTION_REJECTED' }); expect(adapter.questionSource()).toBeDefined(); await expect(adapter.questionSource()!.ask('q', new AbortController().signal)).rejects.toThrow('remote question unavailable'); await expect(adapter.request({ kind: 'interrupt' }, new AbortController().signal)).resolves.toBeUndefined(); adapter.disconnect()
    const noLease = new RemoteSessionAdapter({ ...fixture.transport, negotiate: async () => ({ protocol: '1', capabilities: ['session'] as const }) }); await noLease.connect('s1'); await expect(noLease.acquireWriteLease()).resolves.toMatchObject({ code: 'BLUE_CAPABILITY_ABSENT' }); await expect(noLease.releaseWriteLease()).resolves.toMatchObject({ ok: true }); await expect(noLease.questionSource()!.approve('q', new AbortController().signal)).rejects.toThrow('remote approval unavailable'); noLease.dispose(); expect(noLease.questionSource()).toBeUndefined(); await expect(noLease.request({ kind: 'interrupt' }, new AbortController().signal)).rejects.toThrow('remote action unavailable'); await expect(noLease.snapshot(new AbortController().signal)).rejects.toThrow('remote session unavailable')
    const leased = transportFixture(); const releaseError = { ...leased.transport, releaseWriteLease: async () => { throw 'release down' } }; const leasedAdapter = new RemoteSessionAdapter(releaseError); await leasedAdapter.connect('s1'); await expect(leasedAdapter.acquireWriteLease()).resolves.toMatchObject({ ok: true }); await expect(leasedAdapter.releaseWriteLease()).resolves.toMatchObject({ code: 'BLUE_ACTION_REJECTED', message: 'release down' }); const releaseErrorObject = transportFixture(); const releaseErrorAdapter = new RemoteSessionAdapter({ ...releaseErrorObject.transport, releaseWriteLease: async () => { throw new Error('release down') } }); await releaseErrorAdapter.connect('s1'); await releaseErrorAdapter.acquireWriteLease(); await expect(releaseErrorAdapter.releaseWriteLease()).resolves.toMatchObject({ code: 'BLUE_ACTION_REJECTED' }); const abortLease = new AbortController(); const abortTransport = { ...leased.transport, acquireWriteLease: async (_id: string, signal: AbortSignal) => new Promise<never>((_resolve, reject) => signal.addEventListener('abort', () => reject(new Error('aborted')), { once: true })) }; const abortAdapter = new RemoteSessionAdapter(abortTransport); await abortAdapter.connect('s1'); const aborting = abortAdapter.acquireWriteLease(abortLease.signal); abortLease.abort(); await expect(aborting).resolves.toMatchObject({ code: 'BLUE_ABORTED' }); const preAborted = new AbortController(); preAborted.abort(); await expect(abortAdapter.acquireWriteLease(preAborted.signal)).resolves.toMatchObject({ code: 'BLUE_ABORTED' }); const stringLease = new RemoteSessionAdapter({ ...leased.transport, acquireWriteLease: async () => { throw 'lease down' } }); await stringLease.connect('s1'); await expect(stringLease.acquireWriteLease()).resolves.toMatchObject({ code: 'BLUE_ACTION_REJECTED', message: 'lease down' }); abortAdapter.dispose(); leasedAdapter.dispose(); releaseErrorAdapter.dispose(); stringLease.dispose()
  })
})

describe('ProjectionRegistry', () => {
  it('registers independent sessions, resumes, and unloads cleanly', async () => {
    const listeners = new Map<string, (event: { seq: number; sessionId: string; event: number }) => void>()
    const source = { snapshot: vi.fn(async () => ({ watermark: 2, value: [1, 2] })), subscribe: vi.fn((id: string, _seq: number, next: (event: { seq: number; sessionId: string; event: number }) => void) => { listeners.set(id, next); return () => { if (listeners.get(id) === next) listeners.delete(id) } }) }
    const registry = new ProjectionRegistry(); const registration = registry.register('sum', { init: () => 0, apply: (state: number, event: number) => state + event }, source); await expect(registry.attach<number>('sum', 's1')).resolves.toMatchObject({ ok: true, state: 3, watermark: 2 }); await expect(registry.attach<number>('sum', 's2')).resolves.toMatchObject({ ok: true }); const seen: number[] = []; const off = registry.subscribe<number>('sum', 's1', state => seen.push(state)); listeners.get('s1')?.({ seq: 2, sessionId: 's1', event: 9 }); listeners.get('s2')?.({ seq: 3, sessionId: 's2', event: 8 }); listeners.get('s1')?.({ seq: 4, sessionId: 's1', event: 5 }); expect(registry.snapshot<number>('sum', 's1')).toMatchObject({ state: 8, watermark: 4 }); expect(seen).toEqual([3, 8]); off(); registry.detach('sum', 's1'); expect(registry.snapshot<number>('sum', 's1').state).toBeUndefined(); registration.dispose(); registration.dispose(); await expect(registry.attach('sum', 's1')).resolves.toMatchObject({ code: 'BLUE_CAPABILITY_ABSENT' }); const cleanupSource = { snapshot: async () => ({ watermark: 0, value: [] as number[] }), subscribe: () => () => undefined }; registry.register('cleanup', { init: () => 0, apply: (state: number) => state }, cleanupSource); await registry.attach('cleanup', 's1'); registry.dispose()
  })
  it('rejects duplicate keys, absent subscriptions, and aborted baseline', async () => {
    const registry = new ProjectionRegistry(); const source = { snapshot: async (_id: string, signal: AbortSignal) => { await new Promise<void>(resolve => signal.addEventListener('abort', () => resolve(), { once: true })); return { watermark: 0, value: [] as number[] } }, subscribe: () => () => undefined }; registry.register('x', { init: () => 0, apply: (state: number) => state }, source); expect(() => registry.register('x', { init: () => 0, apply: (state: number) => state }, source)).toThrow(); const controller = new AbortController(); const pending = registry.attach('x', 's1', controller.signal); controller.abort(); await expect(pending).resolves.toMatchObject({ code: 'BLUE_ABORTED' }); const absentOff = registry.subscribe('missing', 's1', () => undefined); absentOff(); registry.dispose()
  })
})

describe('CurrentSessionBinding and plugins', () => {
  it('switches with abort-before-detach and rejects stale attach', async () => {
    const source = { snapshot: vi.fn(async () => ({ watermark: 0, value: snap() })), subscribe: () => () => undefined, request: vi.fn(async () => undefined) }; const session = new SessionBridge({ source }); const actions = new ActionCoordinator(); const binding = new CurrentSessionBinding(session, actions); const seen: string[] = []; binding.subscribe(value => seen.push(value?.id ?? 'none')); await expect(binding.switchTo(source, 'custom')).resolves.toMatchObject({ ok: true }); expect(binding.sessionId).toBe('custom'); expect(binding.snapshot?.id).toBe('s1'); const defaultBinding = new CurrentSessionBinding(new SessionBridge({ source }), new ActionCoordinator()); await expect(defaultBinding.switchTo(source)).resolves.toMatchObject({ ok: true }); expect(defaultBinding.sessionId).toBe('s1'); defaultBinding.dispose(); binding.detach(); expect(seen).toEqual(['none', 's1', 'none']); binding.dispose(); const absent = new CurrentSessionBinding(new SessionBridge(), new ActionCoordinator()); await expect(absent.switchTo(undefined)).resolves.toMatchObject({ code: 'BLUE_CAPABILITY_ABSENT' }); absent.dispose()
    let release!: () => void; const slowSource = { snapshot: async () => new Promise<{ watermark: number; value: ReturnType<typeof snap> }>(resolve => { release = () => resolve({ watermark: 0, value: snap('slow') }) }), subscribe: () => () => undefined, request: async () => undefined }; const stale = new CurrentSessionBinding(new SessionBridge({ source: slowSource }), new ActionCoordinator()); const pending = stale.switchTo(slowSource); stale.detach(); release(); await expect(pending).resolves.toMatchObject({ code: 'BLUE_ACTION_REJECTED' });
    const cleanups: (() => void)[] = []; const provided = new Map<string, unknown>(); const ctx = { provide: (key: string, value: unknown) => provided.set(key, value), effect: (fn: () => () => void) => { const cleanup = fn(); cleanups.push(cleanup); return cleanup }, plugin: (plugin: { apply(ctx: never): void }) => plugin.apply(ctx as never) } as never; projectionRegistryPlugin().apply(ctx); sessionRuntimePlugin().apply(ctx); apply(ctx); expect(provided.has('blueProjectionRegistry')).toBe(true); expect(provided.has('blueSessionBinding')).toBe(true); for (const cleanup of cleanups) cleanup(); const registered = new CurrentSessionBinding(new SessionBridge(), new ActionCoordinator()); const unsubscribe = registered.subscribe(() => undefined); unsubscribe(); expect(invariantName).toBe('blue-remote-invariant'); invariantApply(ctx)
  })
})
